// Generated by CoffeeScript 1.3.1
(function() {
  var total, totalPrice;

  totalPrice = function(price, discountPercent, taxPercent) {
    var discount, tax;
    if (discountPercent == null) {
      discountPercent = 0;
    }
    if (taxPercent == null) {
      taxPercent = 10;
    }
    discount = price * (discountPercent / 100);
    tax = (price - discount) * (taxPercent / 100);
    return price - discount + tax;
  };

  total = totalPrice(100, 50, 20);

  console.log("total price = " + total);

}).call(this);
