// Generated by CoffeeScript 1.3.1
(function() {
  var attn, billTo, shipTo, _ref, _ref1;

  billTo = {};

  billTo.street = "111 Accounting St.";

  billTo.city = "State College";

  shipTo = {};

  shipTo.street = "222 Warehouse Bldv.";

  shipTo.city = "Bellefonte";

  shipTo.attn = {
    name: "John Doe",
    title: "Mr."
  };

  attn = (_ref = shipTo != null ? (_ref1 = shipTo.attn) != null ? _ref1.name : void 0 : void 0) != null ? _ref : "N/A";

  console.log("Attn: " + attn);

}).call(this);
