// Generated by CoffeeScript 1.3.1
(function() {
  var attn, billTo, city, shipTo, _ref, _ref1, _ref2;

  billTo = {};

  billTo.street = "111 Accounting St.";

  billTo.city = "State College";

  shipTo = {};

  shipTo.street = "222 Warehouse Bldv.";

  shipTo.city = "Bellefonte";

  shipTo.attn = {
    name: "John Doe",
    title: "Mr."
  };

  city = (_ref = shipTo != null ? shipTo.city : void 0) != null ? _ref : billTo.city;

  console.log("City: " + city);

  attn = (_ref1 = shipTo != null ? (_ref2 = shipTo.attn) != null ? _ref2.name : void 0 : void 0) != null ? _ref1 : "N/A";

  console.log("Attn: " + attn);

}).call(this);
