// Generated by CoffeeScript 1.3.1
(function() {
  var billTo, city, shipTo, _ref;

  billTo = {};

  billTo.street = "111 Accounting St.";

  billTo.city = "State College";

  shipTo = {};

  shipTo.street = "222 Warehouse Bldv.";

  shipTo.city = "Bellefonte";

  shipTo.attn = {
    name: "John Doe",
    title: "Mr."
  };

  city = (_ref = shipTo != null ? shipTo.city : void 0) != null ? _ref : billTo.city;

  console.log("City: " + city);

}).call(this);
