// Generated by CoffeeScript 1.3.1
(function() {
  var billTo, label, shipTo;

  billTo = {};

  billTo.street = "111 Bill To St.";

  billTo.city = "State College";

  shipTo = {};

  shipTo.street = "222 Ship To St.";

  shipTo.city = "Bellefonte";

  label = shipTo != null ? shipTo : billTo;

  console.log("" + label.street);

}).call(this);
