// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    $('#btnTest1').click(function() {
      return alert(this.value);
    });
    $('#btnTest2').click(function() {
      var url,
        _this = this;
      url = "file:///Users/hector/dev/coffee/intro-to-coffeescript/10_context.txt";
      return $.get(url, function(data) {
        return alert(_this.value);
      });
    });
  });

}).call(this);
