// Generated by CoffeeScript 1.3.1
(function() {
  var InvoiceForm;

  InvoiceForm = (function() {

    InvoiceForm.name = 'InvoiceForm';

    function InvoiceForm(customer) {
      this.customer = customer;
    }

    InvoiceForm.prototype.calculateTotal = function() {
      var total;
      total = 10;
      return alert("" + this.customer + " your total is " + total);
    };

    return InvoiceForm;

  })();

  $(function() {
    var invoice;
    invoice = new InvoiceForm("Acme Corporation");
    invoice.calculateTotal();
    return $('#btnCalculate').click(invoice.calculateTotal);
  });

}).call(this);
