// Generated by CoffeeScript 1.3.1
(function() {
  var city, forecast, temp, weatherReport, _ref;

  weatherReport = function(location) {
    return ["State College, PA", 72, "Sunny"];
  };

  _ref = weatherReport("16801"), city = _ref[0], temp = _ref[1], forecast = _ref[2];

  console.log("" + city + ": " + temp + " " + forecast);

}).call(this);
