// Generated by CoffeeScript 1.3.1
(function() {
  var attention, email, fetchCustomer, _ref;

  fetchCustomer = function(id) {
    var customer;
    customer = {
      name: "Acme Corporation",
      address: "123 desert",
      attention: "Wile E. Coyote",
      email: "wile@acme.com"
    };
    return customer;
  };

  _ref = fetchCustomer(1), attention = _ref.attention, email = _ref.email;

  console.log("" + attention + " " + email);

}).call(this);
