// Generated by CoffeeScript 1.3.1
(function() {
  var c, color, colors, i, toUpper, upper, _i, _j, _len, _len1;

  colors = ['red', 'blue', 'white'];

  console.log("Sample 1 (loop) ------------");

  for (_i = 0, _len = colors.length; _i < _len; _i++) {
    color = colors[_i];
    console.log(color);
  }

  console.log("\r\nSample 2 (loop with i) ------------");

  for (i = _j = 0, _len1 = colors.length; _j < _len1; i = ++_j) {
    color = colors[i];
    console.log(i, color);
  }

  console.log("\r\nSample 3 (comprehension) ------------");

  toUpper = function(value) {
    return value.toUpperCase();
  };

  upper = (function() {
    var _k, _len2, _results;
    _results = [];
    for (_k = 0, _len2 = colors.length; _k < _len2; _k++) {
      c = colors[_k];
      _results.push(toUpper(c));
    }
    return _results;
  })();

  console.log(upper);

}).call(this);
