// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    $("#btnSave").click(function() {
      var r, _i, _len, _ref, _results;
      _ref = $(".required");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        r = _ref[_i];
        if ($(r).val() === "") {
          _results.push($(r).addClass("missing"));
        } else {
          _results.push($(r).removeClass("missing"));
        }
      }
      return _results;
    });
  });

}).call(this);
